# Generated by Django 5.1.1 on 2024-10-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_dz_post_alter_news_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dz_post',
            options={'verbose_name': 'Новость_ДЗ', 'verbose_name_plural': 'Новости_ДЗ'},
        ),
    ]
